### ISSUE TITLE
Relationship field not loading all post types

### ISSUE THREAD

**Issue by trinef** [DekodeInteraktiv/hogan-grid#3]
When using filter 'hogan/module/grid/static_content_post_types' to add an array with additional post type to the relationship field for static content, it only works when this module is added to a custom post type. When used on posts and pages the post list in the field only shows pages and posts.

On pages and posts: http://d.pr/i/trsmDB
On custom post type: http://d.pr/i/ymTHlG

**Comment by walbo** [comment]
Is this still a problem @trinef? Look like it may be fixed without closing this issue?

**Comment by trinef** [comment]
Fixed.
